list(APPEND CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR})
MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

function(simple_build dir type)
	string(CONCAT scriptfile ${dir} "/" "build.cmake")
	if(EXISTS "${PROJECT_SOURCE_DIR}/${scriptfile}")
		include(${scriptfile})
	endif()
	file(GLOB srcfiles ${dir}/*.cpp)
	set(alldeps "")
	if(deps)
		list(APPEND alldeps ${deps})
	endif()
	if(public_deps)
		list(APPEND alldeps ${public_deps})
	endif()
	FOREACH(alldep ${alldeps})
		string(REPLACE "::" ";" parts ${alldep})
		list(GET parts 0 pkg)
		list(LENGTH parts len)
		if(${len} GREATER 1)
			list(SUBLIST parts 1 -1 comps)
		else()
			set(comps "")
		endif()
		find_package(${pkg} REQUIRED ${comps})
	ENDFOREACH()
	string(REPLACE "/" "_" tgt ${dir})
	if(${type} STREQUAL "lib")
		add_library(${tgt} ${srcfiles})
	else()
		add_executable(${tgt} ${srcfiles})
	endif()
	target_include_directories(${tgt} PRIVATE ${PROJECT_SOURCE_DIR})
	if(publicdeps)
		target_link_libraries(${tgt} PUBLIC ${publicdeps})
	endif()
	if(deps)
		target_link_libraries(${tgt} PRIVATE ${deps})
	endif()
	if(libs)
		foreach(lib ${libs})
			target_link_libraries(${tgt} PRIVATE "lib_${lib}")
		endforeach()
	endif()
endfunction()

function(autobuild)
	SUBDIRLIST(SUBDIRS "${PROJECT_SOURCE_DIR}/lib")
	foreach(subdir ${SUBDIRS})
		message(STATUS "Building lib ${subdir}")
		simple_build("lib/${subdir}" lib)
	endforeach()
	SUBDIRLIST(SUBDIRS "${PROJECT_SOURCE_DIR}/app")
	foreach(subdir ${SUBDIRS})
		message(STATUS "Building app ${subdir}")
		simple_build("app/${subdir}" lib)
	endforeach()
endfunction()
